
---
title:  "Wrangle OpenStreetMaps Data and Query with SQL"
description: "Ioannis Karakasoglou Breier"
theme: jekyll-theme-minimal
google_analytics: "UA-100574901-1"
exclude:
  - Gemfile
  - Gemfile.lock
---
